import GRDB

enum InitialMigration: DatabaseMigration {
    static var name: String { "initial" }

    static func migrate(_ db: Database) throws {
        try db.create(table: "user") { t in
            // Basic fields
            t.primaryKey("id", .integer)
            t.column("first_name", .text).notNull()
            t.column("last_name", .text)
            t.column("deactivated", .integer)
            t.column("ap_id", .text)
            // Optional fields
            t.column("status", .text)
            t.column("url", .text)
            t.column("nickname", .text)
            t.column("maiden_name", .text)
            t.column("sex", .text)
            t.column("bdate", .date)
            t.column("home_town", .text)
            t.column("relation", .text)
            t.column("relation_partner", .jsonText)
            t.column("custom", .jsonText)
            t.column("city", .text)
            t.column("connections", .jsonText)
            t.column("site", .text)
            t.column("activities", .text)
            t.column("interests", .text)
            t.column("music", .text)
            t.column("movies", .text)
            t.column("tv", .text)
            t.column("books", .text)
            t.column("games", .text)
            t.column("quotes", .text)
            t.column("about", .text)
            t.column("personal", .jsonText)
            t.column("last_seen", .jsonText)
            t.column("domain", .text)
            t.column("blocked", .boolean)
                .notNull()
                .defaults(to: false)
            t.column("blocked_by_me", .boolean)
                .notNull()
                .defaults(to: false)
            t.column("can_post", .boolean)
                .notNull()
                .defaults(to: false)
            t.column("can_see_all_posts", .boolean)
                .notNull()
                .defaults(to: false)
            t.column("can_send_friend_request", .boolean)
                .notNull()
                .defaults(to: false)
            t.column("can_write_private_message", .boolean)
                .notNull()
                .defaults(to: false)
            t.column("friend_status", .text)
                .notNull()
                .defaults(to: "none")
            t.column("is_friend", .boolean)
                .notNull()
                .defaults(to: false)
            t.column("is_favorite", .boolean)
                .notNull()
                .defaults(to: false)
            t.column("is_hidden_from_feed", .boolean)
                .notNull()
                .defaults(to: false)
            t.column("wall_default", .text)
                .notNull()
                .defaults(to: "owner")
            t.column("photo_50", .text)
            t.column("photo_100", .text)
            t.column("photo_200", .text)
            t.column("photo_400", .text)
            t.column("photo_max", .text)
            t.column("photo_200_orig", .text)
            t.column("photo_400_orig", .text)
            t.column("photo_max_orig", .text)
            t.column("photo_id", .text)
            t.column("has_photo", .boolean)
                .notNull()
                .defaults(to: false)
            t.column("first_name_gen", .text)
            t.column("counters", .jsonText)
        }

        try db.create(table: "wall_post") { t in
            t.primaryKey("id", .integer)
            t.column("user_owner_id", .integer)
            t.column("group_owner_id", .integer)
            t.column("from_user_id", .integer)
            t.column("from_group_id", .integer)
            t.column("ap_id", .text).notNull()
            t.column("url", .text).notNull()
            t.column("date", .datetime).notNull()
            t.column("text", .text)
            t.column("likes", .jsonText)
            t.column("attachments", .jsonText)
            t.column("content_warning", .text)
            t.column("can_delete", .boolean).notNull()
            t.column("can_edit", .boolean).notNull()
            t.column("privacy", .text)
            t.column("reposts", .jsonText)
            t.column("post_source", .jsonText)
            t.column("comments", .jsonText)
            t.column("is_mastodon_style_repost", .boolean)
            t.column("can_pin", .boolean)
            t.column("is_pinned", .boolean)
        }

        try db.create(table: "repost") { t in
            t.primaryKey("repost_id", .integer)
                .references("wall_post", onDelete: .cascade)
            t.primaryKey("reposted_id", .integer)
                .references("wall_post", onDelete: .cascade)
            t.column("is_mastodon_style", .boolean).notNull().defaults(to: false)
        }
    }
}
