test_configuration:
  - target: Smithereen
  - imports:
    - SmithereenAPI
  - test_target_path: ${PROJECT_DIR}/Tests
  - template_file_path: XCTestPreviewTests.stencil
  - simulator_device: "iPhone17,3"
  - snapshot_devices:
      - iPhone 16
